version: "3.3"
services:
  database:
    image: postgres:10.5
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "backend"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - nerdpipe:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    ports:
      - "4000:4000"
    restart: always
    volumes:
      - "./backend:/app"
      - "./backend/node_modules:/app/node_modules"
    environment:
      - HOME=/app
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - "./frontend:/app"
      - "./frontend/node_modules:/app/node_modules"
    environment:
      - HOME=/app
      - NODE_ENV=development

volumes:
  ? nerdpipe
