projects:
  app:
    schemaPath: src/generated/app.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
      codegen:
        - generator: graphql-binding
          language: typescript
          input:
            schema: src/typeGenerator.ts
          output:
            binding: src/generated/app.ts
