FROM node:8.11.3

RUN mkdir /app
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json .
COPY yarn.lock .

RUN yarn install --ignore-platform

# start app
CMD ["yarn", "start"]
